#dns:
#  build: dns
#  hostname: dns
#  expose:
#    - 53
#    - 8053
#  volumes: 
#    - "/data/alfresco/dns:/data"
#  ports:
#    - "8053:8053"
haveged:
  image: harbur/haveged:1.7c-1
  privileged: true
consul:
  image: gliderlabs/consul-server
  ports:
    - "8500:8500"
alfresco:
  build: alfresco
  hostname: alfresco
  expose: 
    - "2021"
    - "7070"
    - "8080"
  links: 
    - consul
    - mysql
    - solr
    - postfix
  ports:
    - "8081:8080"
  volumes: 
    - /data/alfresco/repo:/data
share:
  build: share
  hostname: share
  expose:
    - 8080
  ports:
    - "8080:8080"
  volumes: 
    - /data/alfresco/share:/data
  links:
    - alfresco
    - consul
solr:
  build: solr
  hostname: solr
  volumes:
    - /data/alfresco/solr/data:/data
    - /data/alfresco/solr/content:/content
  links: 
    - consul
#postgresql:
#  hostname: postgresql
#  image: sameersbn/postgresql
#  volumes:
#    - /data/alfresco/postgresql:/var/lib/postgresql
#  environment:
#    DB_NAME: alfresco
#    DB_USER: alfresco
#    DB_PASS: alfresco
mysql:
  hostname: mysql
  image: "mysql:5.6"
  volumes: 
    - /data/alfresco/mysql:/var/lib/mysql
  environment:
    MYSQL_DATABASE: alfresco
    MYSQL_USER: alfresco
    MYSQL_PASSWORD: alfresco
    MYSQL_ROOT_PASSWORD: alfresco
postfix:
  hostname: postfix
  image: "catatnight/postfix"
  ports:
    - "25:25"
  environment: 
    maildomain: "alfresco.local"
    smtp_user: "mailuser:password"

